### ISSUE TITLE
debugger not picking up breakpoints

### ISSUE THREAD

**Issue by lexihaj1979** [cs50/harvard.cs50.debug#37]
Hi
today debugger has suddenly stopped seeing breakpoints - getting this message when I run debug50
.
Looks like you haven't set any breakpoints. Set at least one breakpoint by clicking to the left of a line number and then re-run debug50.

Is there a fix for this?
Thanks

**Comment by kzidane** [comment]
Are you sure you're running `debug50` on the right file? Could you post a screenshot of the error, showing that breakpoints are set in the correct file please?

**Comment by lexihaj1979** [comment]
Hi! I think so! Hopefully I'm not doing something silly...
![image](https://user-images.githubusercontent.com/52657086/81843855-846dd680-954e-11ea-9fcf-63497004e9ff.png)

**Comment by kzidane** [comment]
Could you hover over the `runoff.c` tab to see its path? It's possible that you have two different `runoff.c` files, one at `~/pset3/runoff.c` and the other is at `~/pset3/runoff/runoff.c`.

**Comment by lexihaj1979** [comment]
![image](https://user-images.githubusercontent.com/52657086/81845983-acab0480-9551-11ea-9d34-a678d98af9a9.png)

**Comment by kzidane** [comment]
As you can see this is `runoff.c` that lives directly under the `pset3` folder, which suggests that the breakpoints are set in the wrong file since you're trying to run an executable that lives under `~/pset3/runoff/`.

**Comment by lexihaj1979** [comment]
oh dear.  thanks so much! won't do that again...

**Comment by lexihaj1979** [comment]
ha no wonder there were no errors when I compiled
