### ISSUE TITLE
debug50 doesn't give any output or reaction (Edit: Now it says no breakpoints set no matter what)

### ISSUE THREAD

**Issue by aneekan** [cs50/harvard.cs50.debug#38]
I just learnt about debug50 last night in the week 2 lecture so this might just be noob problems but yeah. I put a breakpoint and saved the file and compiled it. It runs fine normally(with a bug ofc) but when I try to run it with debug50 it just looks for input and doesnt give any output and the debugger doesn't work either. 
![Capture](https://user-images.githubusercontent.com/69073591/89368364-fd696e00-d6f8-11ea-811c-1646a5347049.PNG)
![s](https://user-images.githubusercontent.com/69073591/89368408-1d009680-d6f9-11ea-80ad-bf556d1ccc74.PNG)

**Comment by kzidane** [comment]
Is it possible that your program has an infinite loop or blocking on something else before the breakpoint? Have you tried setting a breakpoint on the first line inside the `main` function?

**Comment by aneekan** [comment]
I've tried using this on working programs too. And set breakpoints on the first line inside the main function. This specific program I found my error and fixed it but not being able to use debug50 has been a big bugger. I've tried on other systems and browsers too so not a problem with that.

**Comment by aneekan** [comment]
update, now it says no breakpoints set no matter how many i have set. I tried removing and readding. I read the other issue similar to this and ran that diff code and it output a whole lot of lines. I tried doing update50 but it says command not found so that's all i could do for now.

**Comment by kzidane** [comment]
Are you absolutely sure the breakpoints are set in the correct file? What if you click CS50 IDE > Reset Settings on the top-left corner and try again?

**Comment by aneekan** [comment]
![Capture 1](https://user-images.githubusercontent.com/69073591/90481827-083bee00-e150-11ea-92e4-a1f9131c2c61.PNG)
![Capture](https://user-images.githubusercontent.com/69073591/90481838-0d993880-e150-11ea-8efe-b7cfe242f320.PNG)
Reset settings and tried it on a working program. Same result.

**Comment by kzidane** [comment]
If you open Chrome's console by pressing Ctrl + Shift + J then run `debug50`, do you see any errors in the console? And can you hover over the `cash.c` tab to show me the path please?

**Comment by aneekan** [comment]
![Capture](https://user-images.githubusercontent.com/69073591/90588412-30335c00-e1f9-11ea-9113-621d6c485ecc.PNG)
The path is /pset1/cash/cash.c

**Comment by aneekan** [comment]
![Capture](https://user-images.githubusercontent.com/69073591/90588542-7e485f80-e1f9-11ea-8fde-b0995978f776.PNG)
It started with that first error and then the next error kept repeating with a delay. The path is /pse1/cash/cash.c

**Comment by kzidane** [comment]
The console reports 10 errors but I see only 4 in the screenshot. Are they all the same? And does the same thing happen on the latest version of Firefox?

**Comment by aneekan** [comment]
![Capture](https://user-images.githubusercontent.com/69073591/90803028-c2407f00-e335-11ea-8147-eb3a31e92106.PNG)
I haven't run debug50 and the console already had errors. These errors always show and then that last error keeps repeating every 250 seconds. 
Not sure about firefox but debug50 works the same way for safari on my mac.

**Comment by kzidane** [comment]
Yeah, these are unrelated. Could you try the latest version of Firefox please?

**Comment by aneekan** [comment]
![Capture 1](https://user-images.githubusercontent.com/69073591/90803683-c15c1d00-e336-11ea-862a-8b526f3e8a7e.PNG)
![Capture](https://user-images.githubusercontent.com/69073591/90803699-c620d100-e336-11ea-9ab9-b2351a9c254d.PNG)
Same issue :/
Just downloaded firefox so definitely the latest version.

**Comment by aneekan** [comment]
![Capture](https://user-images.githubusercontent.com/69073591/90803885-0a13d600-e337-11ea-95b1-275cbaa055f0.PNG)
Here's the errors in the firefox console.

**Comment by kzidane** [comment]
And do you see the same behavior where debug50 just hangs?

Kareem

**Comment by aneekan** [comment]
It used to do that where it just hanged like in the originals pictures I shared but now it says no breakpoints. Hasn't hanged for a while.

**Comment by kzidane** [comment]
Can you open the debug panel on the right hand-side and show me a screenshot of it please?

**Comment by aneekan** [comment]
![Screenshot_2020-08-21-00-02-22-424_com android chrome](https://user-images.githubusercontent.com/69073591/90811435-3c770080-e342-11ea-85f0-23050ae7b199.png)
![Screenshot_2020-08-21-00-05-19-807_com android chrome](https://user-images.githubusercontent.com/69073591/90811439-3f71f100-e342-11ea-99d8-a562d4d37554.png)
First time I tried it it doesn't show any breakpoints on the panel but if I deactivate all breakpoints and make new ones it shows there but still doesn't run. These are screenshots from my phone yes but I've tested this earlier, gives the same result on my computer too with the breakpoints not showing first and then showing.

**Comment by sqUadow** [comment]
I was just now having the same problem.  the cs50 ide had the file open on another computer and after i closed it breakpoints were once again recognized.

**Comment by aneekan** [comment]
I only ever use it one device, one tab at a time so I don't think that applies to me unfortunately.

**Comment by aneekan** [comment]
I'm now done with everything in the ide so this is no longer relevant to me but the problem is still present so yeah.

**Comment by aneekan** [comment]
idk what happened but I was simply checking and it works now.
