### ISSUE TITLE
Run button

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.debug#4]
@dmalan @glennholloway 

According to an earlier conversation with Dan, the old GDB debugging runner won't work well with the new shim. Been getting reports that the debugger doesn't work when launched via the Run button. It seems to work when launched via

```bash
debug50 foo
```

Confirmed that it doesn't work neither when launched via the Run button nor via `debug50 -o foo` (which, per the Readme, acts like clicking the Run button).

The Run button, for some reason, currently appears only in more comfy. Are we removing these options altogether, or adjusting so that they somehow run `debug50 foo`?

**Comment by kzidane** [comment]
@dmalan any input on keeping or removing the "Run" button before pushing to C9? It should behave correctly, if the C (make) runner exists online, but it doesn't. Would have to ask C9 about why it's missing (as it should be provided by [one of the core plugins](https://github.com/c9/c9.ide.run/blob/master/runners/C%20(make).run)), but probably not worth it, if we're removing?

Currently the "Run" button exists in more-comfy only (not sure why). If we're keeping, should we make it available in both modes?

**Comment by dmalan** [comment]
Does `debug50` now work as expected? Doesn't stop working on folks after a while? If so, let's get rid of the button in both modes.

**Comment by dmalan** [comment]
+ @glennholloway

**Comment by kzidane** [comment]
@dmalan, haven't had issues with `debug50`, after the latest fixes. 

Our plugin also provides a way to use C9's default run and debug systems through `debug50 -o` (opens _new_ terminal tab with all the buttons, text fields, etc), which works fine locally, but doesn't seem to work online (though not sure if it will work after we push our fixes). Should we keep or remove that option?

**Comment by dmalan** [comment]
Any reason to keep it? For C, I find the old, default UI (with new terminal
tab with all the buttons) very confusing anyway.

**Comment by kzidane** [comment]
+1 for simplicity! Will remove!

**Comment by kzidane** [comment]
`debug50 -o` removed per 34ca117cdd. Run button removed per cs50/harvard.cs50.simple@62bf7aabeb6cefd.
